// Demo mock data — used when database is not available

export const MOCK_CLINIC = {
  id: 'demo-clinic-001',
  name: '台北功能醫學診所（示範）',
  slug: 'taipei-wellness',
}

export const MOCK_USERS = [
  { id: 'demo-admin-001', name: '王診所長', email: 'admin@taipei-wellness.com', role: 'CLINIC_ADMIN', createdAt: new Date('2026-01-01'), _count: { patients: 0 } },
  { id: 'demo-doctor-001', name: '王大明 醫師', email: 'wang@taipei-wellness.com', role: 'DOCTOR', createdAt: new Date('2026-01-05'), _count: { patients: 1 } },
]

export const MOCK_PATIENTS = [
  {
    id: 'demo-patient-001',
    chartNumber: 'FM-2026-00421',
    firstName: '美玲',
    lastName: '陳',
    dateOfBirth: new Date('1984-05-15'),
    gender: 'FEMALE',
    email: 'meiling.chen@example.com',
    phone: '0912-345-678',
    notes: '模擬教學患者資料',
    clinicId: 'demo-clinic-001',
    doctorId: 'demo-doctor-001',
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-01'),
    doctor: { id: 'demo-doctor-001', name: '王大明 醫師' },
    _count: { reports: 1 },
  },
]

export const MOCK_REPORTS = [
  {
    id: 'demo-report-001',
    reportDate: new Date('2026-03-10'),
    status: 'PARSED',
    blobName: 'demo/functional_medicine_report.pdf',
    originalName: 'functional_medicine_report.pdf',
    fileSizeBytes: 245760,
    parsedData: null,
    parseError: null,
    aiAnalysis: null,
    analysisAt: null,
    createdAt: new Date('2026-03-21'),
    updatedAt: new Date('2026-03-21'),
    patientId: 'demo-patient-001',
    clinicId: 'demo-clinic-001',
    uploadedBy: 'demo-doctor-001',
    patient: MOCK_PATIENTS[0],
    panels: [
      { panelType: 'HORMONE', flagged: true },
      { panelType: 'ALLERGY_FOOD_SENSITIVITY', flagged: true },
      { panelType: 'GI_HEALTH', flagged: true },
      { panelType: 'ORGANIC_ACIDS', flagged: true },
      { panelType: 'TOXIC_ELEMENTS', flagged: true },
      { panelType: 'OXIDATIVE_STRESS', flagged: true },
    ],
  },
]

// Parsed panel values from the sample PDF
export const MOCK_PANELS = [
  {
    id: 'demo-panel-hormone',
    panelType: 'HORMONE',
    flagged: true,
    rawText: '',
    reportId: 'demo-report-001',
    createdAt: new Date(),
    values: {
      cortisolAM: { value: 18.2, unit: 'nmol/L', referenceRange: '13.0 - 24.0', flag: 'NORMAL' },
      cortisolNoon: { value: 5.1, unit: 'nmol/L', referenceRange: '5.0 - 10.0', flag: 'NORMAL' },
      cortisolPM: { value: 2.8, unit: 'nmol/L', referenceRange: '3.0 - 8.0', flag: 'LOW' },
      cortisolNight: { value: 3.9, unit: 'nmol/L', referenceRange: '0.5 - 3.0', flag: 'HIGH' },
      dheaS: { value: 95, unit: 'ug/dL', referenceRange: '120 - 360', flag: 'LOW' },
      cortisolDheasRatio: { value: 6.8, unit: '', referenceRange: '2.0 - 6.0', flag: 'HIGH' },
      tsh: { value: 4.82, unit: 'uIU/mL', referenceRange: '0.45 - 4.50', flag: 'HIGH' },
      freeT4: { value: 1.05, unit: 'ng/dL', referenceRange: '0.82 - 1.77', flag: 'NORMAL' },
      freeT3: { value: 2.1, unit: 'pg/mL', referenceRange: '2.0 - 4.4', flag: 'NORMAL' },
      reverseT3: { value: 28, unit: 'ng/dL', referenceRange: '9.2 - 24.1', flag: 'HIGH' },
      antiTpoAb: { value: 48, unit: 'IU/mL', referenceRange: '< 34', flag: 'HIGH' },
      antiTgAb: { value: 22, unit: 'IU/mL', referenceRange: '< 40', flag: 'NORMAL' },
      estradiol: { value: 185, unit: 'pg/mL', referenceRange: '40 - 400', flag: 'NORMAL' },
      progesterone: { value: 0.8, unit: 'ng/mL', referenceRange: '1.8 - 24.0', flag: 'LOW' },
      testosterone: { value: 18, unit: 'ng/dL', referenceRange: '15 - 70', flag: 'NORMAL' },
      e2P4Ratio: { value: 231, unit: '', referenceRange: '< 200', flag: 'HIGH' },
      shbg: { value: 82, unit: 'nmol/L', referenceRange: '18 - 114', flag: 'NORMAL' },
    },
  },
  {
    id: 'demo-panel-allergy',
    panelType: 'ALLERGY_FOOD_SENSITIVITY',
    flagged: true,
    rawText: '',
    reportId: 'demo-report-001',
    createdAt: new Date(),
    values: {
      igeTotal: { value: 285, unit: 'IU/mL', referenceRange: '< 100', flag: 'HIGH' },
      dustMite: { value: 4.5, unit: 'kU/L', referenceRange: '< 0.35', flag: 'HIGH' },
      cockroach: { value: 2.1, unit: 'kU/L', referenceRange: '< 0.35', flag: 'HIGH' },
      mold: { value: 0.52, unit: 'kU/L', referenceRange: '< 0.35', flag: 'HIGH' },
      pollen: { value: 0.28, unit: 'kU/L', referenceRange: '< 0.35', flag: 'NORMAL' },
      catDander: { value: 0.18, unit: 'kU/L', referenceRange: '< 0.35', flag: 'NORMAL' },
      foodSensitivities: [
        { food: '牛奶', igG: 58.3, unit: 'U/mL', level: 'Class 3', severity: 'severe' },
        { food: '蛋白', igG: 42.7, unit: 'U/mL', level: 'Class 3', severity: 'severe' },
        { food: '小麥/麩質', igG: 51.9, unit: 'U/mL', level: 'Class 3', severity: 'severe' },
        { food: '蛋黃', igG: 35.1, unit: 'U/mL', level: 'Class 2', severity: 'moderate' },
        { food: '黃豆', igG: 28.4, unit: 'U/mL', level: 'Class 2', severity: 'moderate' },
        { food: '豬肉', igG: 22.8, unit: 'U/mL', level: 'Class 2', severity: 'moderate' },
        { food: '酵母', igG: 31.6, unit: 'U/mL', level: 'Class 2', severity: 'moderate' },
        { food: '花生', igG: 15.2, unit: 'U/mL', level: 'Class 1', severity: 'mild' },
        { food: '鮭魚', igG: 6.2, unit: 'U/mL', level: 'Class 0', severity: 'normal' },
        { food: '白米', igG: 5.1, unit: 'U/mL', level: 'Class 0', severity: 'normal' },
        { food: '杏仁', igG: 8.7, unit: 'U/mL', level: 'Class 0', severity: 'normal' },
        { food: '鳳梨', igG: 9.3, unit: 'U/mL', level: 'Class 0', severity: 'normal' },
      ],
    },
  },
  {
    id: 'demo-panel-gi',
    panelType: 'GI_HEALTH',
    flagged: true,
    rawText: '',
    reportId: 'demo-report-001',
    createdAt: new Date(),
    values: {
      shannonIndex: { value: 3.2, unit: '', referenceRange: '3.5 - 5.0', flag: 'LOW' },
      firmicutesBacteroidetes: { value: 4.8, unit: '', referenceRange: '1.0 - 3.0', flag: 'HIGH' },
      lactobacillus: { value: 1.2, unit: '%', referenceRange: '3.0 - 8.0', flag: 'LOW' },
      bifidobacterium: { value: 2.8, unit: '%', referenceRange: '5.0 - 15.0', flag: 'LOW' },
      akkermansia: { value: 0.3, unit: '%', referenceRange: '1.0 - 4.0', flag: 'LOW' },
      faecalibacterium: { value: 4.1, unit: '%', referenceRange: '5.0 - 15.0', flag: 'LOW' },
      zonulin: { value: 128, unit: 'ng/mL', referenceRange: '< 107', flag: 'HIGH' },
      sIgA: { value: 310, unit: 'ug/mL', referenceRange: '400 - 880', flag: 'LOW' },
      calprotectin: { value: 85, unit: 'ug/g', referenceRange: '< 50', flag: 'HIGH' },
      pancreaticElastase: { value: 380, unit: 'ug/g', referenceRange: '> 200', flag: 'NORMAL' },
      butyrate: { value: 8.2, unit: 'umol/g', referenceRange: '10.0 - 25.0', flag: 'LOW' },
      propionate: { value: 12.5, unit: 'umol/g', referenceRange: '10.0 - 20.0', flag: 'NORMAL' },
      betaGlucuronidase: { value: 2850, unit: 'U/g', referenceRange: '< 2000', flag: 'HIGH' },
    },
  },
  {
    id: 'demo-panel-oa',
    panelType: 'ORGANIC_ACIDS',
    flagged: true,
    rawText: '',
    reportId: 'demo-report-001',
    createdAt: new Date(),
    values: {
      citricAcid: { value: 185, unit: 'mmol/mol Cr', referenceRange: '90 - 280', flag: 'NORMAL' },
      succinicAcid: { value: 38, unit: 'mmol/mol Cr', referenceRange: '5 - 25', flag: 'HIGH' },
      fumaricAcid: { value: 1.8, unit: 'mmol/mol Cr', referenceRange: '0.2 - 3.5', flag: 'NORMAL' },
      malicAcid: { value: 4.2, unit: 'mmol/mol Cr', referenceRange: '0.3 - 3.8', flag: 'HIGH' },
      pyruvicAcid: { value: 12.5, unit: 'mmol/mol Cr', referenceRange: '3.0 - 10.0', flag: 'HIGH' },
      lacticAcid: { value: 28.3, unit: 'mmol/mol Cr', referenceRange: '5.0 - 22.0', flag: 'HIGH' },
      hva: { value: 3.8, unit: 'mmol/mol Cr', referenceRange: '1.5 - 7.0', flag: 'NORMAL' },
      vma: { value: 5.2, unit: 'mmol/mol Cr', referenceRange: '1.0 - 4.5', flag: 'HIGH' },
      hiaa: { value: 2.1, unit: 'mmol/mol Cr', referenceRange: '2.5 - 8.0', flag: 'LOW' },
      quinolinicAcid: { value: 8.5, unit: 'mmol/mol Cr', referenceRange: '1.0 - 6.0', flag: 'HIGH' },
      kynurenicAcid: { value: 1.2, unit: 'mmol/mol Cr', referenceRange: '0.5 - 3.0', flag: 'NORMAL' },
      methylmalonicAcid: { value: 4.8, unit: 'mmol/mol Cr', referenceRange: '0.3 - 3.5', flag: 'HIGH' },
      xanthurenicAcid: { value: 2.1, unit: 'mmol/mol Cr', referenceRange: '0.2 - 1.5', flag: 'HIGH' },
      figlu: { value: 3.2, unit: 'mmol/mol Cr', referenceRange: '0.5 - 2.8', flag: 'HIGH' },
      arabinose: { value: 58, unit: 'mmol/mol Cr', referenceRange: '10 - 42', flag: 'HIGH' },
      dhppa: { value: 0.15, unit: 'mmol/mol Cr', referenceRange: '0.30 - 2.00', flag: 'LOW' },
      cresol: { value: 185, unit: 'mmol/mol Cr', referenceRange: '< 150', flag: 'HIGH' },
      dArabinitol: { value: 42, unit: 'mmol/mol Cr', referenceRange: '15 - 35', flag: 'HIGH' },
    },
  },
  {
    id: 'demo-panel-toxic',
    panelType: 'TOXIC_ELEMENTS',
    flagged: true,
    rawText: '',
    reportId: 'demo-report-001',
    createdAt: new Date(),
    values: {
      mercuryBlood: { value: 8.5, unit: 'ug/L', referenceRange: '< 5.0', flag: 'HIGH' },
      mercuryUrine: { value: 18.2, unit: 'ug/g Cr', referenceRange: '< 4.0', flag: 'HIGH' },
      lead: { value: 3.8, unit: 'ug/dL', referenceRange: '< 3.5', flag: 'HIGH' },
      arsenic: { value: 42, unit: 'ug/L', referenceRange: '< 35', flag: 'HIGH' },
      cadmium: { value: 0.8, unit: 'ug/L', referenceRange: '< 1.0', flag: 'NORMAL' },
      aluminum: { value: 25, unit: 'ug/L', referenceRange: '< 30', flag: 'NORMAL' },
      zinc: { value: 62, unit: 'ug/dL', referenceRange: '70 - 120', flag: 'LOW' },
      selenium: { value: 85, unit: 'ug/L', referenceRange: '70 - 150', flag: 'NORMAL' },
      magnesiumRbc: { value: 3.8, unit: 'mg/dL', referenceRange: '4.2 - 6.8', flag: 'LOW' },
      copper: { value: 145, unit: 'ug/dL', referenceRange: '70 - 140', flag: 'HIGH' },
      cuZnRatio: { value: 2.3, unit: '', referenceRange: '0.7 - 1.5', flag: 'HIGH' },
      ferritin: { value: 18, unit: 'ng/mL', referenceRange: '20 - 200', flag: 'LOW' },
      iodine: { value: 52, unit: 'ug/L', referenceRange: '100 - 300', flag: 'LOW' },
      mehp: { value: 18.5, unit: 'ug/L', referenceRange: '< 10.0', flag: 'HIGH' },
      bpa: { value: 5.2, unit: 'ug/L', referenceRange: '< 2.0', flag: 'HIGH' },
      nonylphenol: { value: 3.8, unit: 'ug/L', referenceRange: '< 2.5', flag: 'HIGH' },
      glyphosate: { value: 1.2, unit: 'ug/L', referenceRange: '< 1.0', flag: 'HIGH' },
    },
  },
  {
    id: 'demo-panel-oxidative',
    panelType: 'OXIDATIVE_STRESS',
    flagged: true,
    rawText: '',
    reportId: 'demo-report-001',
    createdAt: new Date(),
    values: {
      ohdg: { value: 18.5, unit: 'ng/mg Cr', referenceRange: '5.0 - 15.0', flag: 'HIGH' },
      mda: { value: 3.8, unit: 'umol/L', referenceRange: '0.8 - 2.5', flag: 'HIGH' },
      isoprostanes: { value: 285, unit: 'pg/mg Cr', referenceRange: '< 230', flag: 'HIGH' },
      proteinCarbonyls: { value: 1.2, unit: 'nmol/mg', referenceRange: '0.4 - 1.0', flag: 'HIGH' },
      gsh: { value: 620, unit: 'umol/L', referenceRange: '800 - 1200', flag: 'LOW' },
      gssg: { value: 185, unit: 'umol/L', referenceRange: '< 150', flag: 'HIGH' },
      gshGssgRatio: { value: 3.4, unit: '', referenceRange: '> 5.0', flag: 'LOW' },
      sod: { value: 1050, unit: 'U/gHb', referenceRange: '1100 - 1800', flag: 'LOW' },
      gpx: { value: 28, unit: 'U/gHb', referenceRange: '30 - 55', flag: 'LOW' },
      catalase: { value: 185, unit: 'kU/gHb', referenceRange: '150 - 350', flag: 'NORMAL' },
      coq10: { value: 0.42, unit: 'ug/mL', referenceRange: '0.50 - 1.50', flag: 'LOW' },
      vitaminC: { value: 0.35, unit: 'mg/dL', referenceRange: '0.60 - 2.00', flag: 'LOW' },
      vitaminE: { value: 8.5, unit: 'mg/L', referenceRange: '5.5 - 17.0', flag: 'NORMAL' },
      tac: { value: 1.05, unit: 'mmol Trolox eq/L', referenceRange: '1.30 - 1.77', flag: 'LOW' },
    },
  },
]
